# Generated by Django 5.1.4 on 2025-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_rename_recipe_description_recipe_receipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='receipe_image',
            field=models.ImageField(upload_to='recipes/'),
        ),
    ]
