# Generated by Django 5.1.4 on 2025-01-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='receipe_description_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
